[build]
  command = """
    rustup install nightly --profile minimal \
      && cargo doc --no-deps --all-features
    """
  publish = "target/doc"

<<<<<<< HEAD
[build.environment]
  RUSTDOCFLAGS="""
    -D warnings \
    --force-warn rustdoc::redundant-explicit-links \
    --force-warn renamed-and-removed-lints \
    --cfg docsrs \
    --cfg tracing_unstable
    """
  RUSTFLAGS="--cfg tracing_unstable"

||||||| 386969ba
=======
[build.environment]
  RUSTDOCFLAGS="""
    -D warnings \
    --force-warn rustdoc::redundant-explicit-links \
    --force-warn renamed-and-removed-lints \
    --cfg docsrs \
    --html-before-content /opt/build/repo/assets/warning.html \
    --html-in-header /opt/build/repo/assets/noindex.html \
    --html-in-header /opt/build/repo/assets/warning-css.html \
    """

>>>>>>> origin/master
[[redirects]]
  from = "/"
  to = "/tracing"
