[package]
name = "tracing-serde"
<<<<<<< HEAD
version = "0.1.3"
||||||| 386969ba
version = "0.1.2"
=======
version = "0.2.0"
>>>>>>> origin/master
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
description = """
A compatibility layer for serializing trace data with `serde`
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
    "encoding",
]
keywords = ["logging", "tracing", "serialization"]
<<<<<<< HEAD
rust-version = "1.63.0"

[features]
valuable = ["valuable_crate", "valuable-serde", "tracing-core/valuable"]
||||||| 386969ba
=======
rust-version = "1.63.0"

[features]
default = ["std"]
std = ["serde/std", "tracing-core/std"]
>>>>>>> origin/master

[dependencies]
<<<<<<< HEAD
serde = "1"
tracing-core = { path = "../tracing-core", version = "0.1.28"}
||||||| 386969ba
serde = "1"
tracing-core = { path = "../tracing-core", version = "0.1.2"}
=======
serde = { version = "1.0.139", default-features = false, features = ["alloc"] }
tracing-core = { path = "../tracing-core", version = "0.2", default-features = false }
>>>>>>> origin/master

[dev-dependencies]
serde_json = "1.0.82"

[target.'cfg(tracing_unstable)'.dependencies]
valuable_crate = { package = "valuable", version = "0.1.0", optional = true, default-features = false }
valuable-serde = { version = "0.1.0", optional = true, default-features = false }

[badges]
maintenance = { status = "experimental" }

[lints]
workspace = true
