[package]
name = "tracing-macros"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
description = """
Macros for emitting trace events
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing"]
license = "MIT"
rust-version = "1.63.0"

[dependencies]
<<<<<<< HEAD
tracing = { path = "../tracing", version = "0.1.35" }
||||||| 386969ba
tracing = "0.1.18"
=======
tracing = { path = "../tracing", version = "0.2", default-features = false, features = ["std"] }
>>>>>>> origin/master

[dev-dependencies]
<<<<<<< HEAD
tracing-subscriber = { path = "../tracing-subscriber", version = "0.3.0", features = ["env-filter"] }
||||||| 386969ba
tracing-log = "0.1"
env_logger = "0.7"
=======
tracing-subscriber = { path = "../tracing-subscriber", version = "0.3" }
>>>>>>> origin/master

[badges]
maintenance = { status = "experimental" }

[lints]
workspace = true
